# Generated by Django 5.1.1 on 2024-09-14 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmentapiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountpermission',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='investmentapiapp.investmentaccount'),
        ),
    ]
